default_settings: null
behaviors:
  SmartBehaviour:
    trainer_type: sac
    hyperparameters:
      learning_rate: 3.0e-05
      learning_rate_schedule: constant
      batch_size: 256
      buffer_size: 200000
      buffer_init_steps: 1000
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: true
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: false
      hidden_units: 20
      num_layers: 2
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
    init_path: results\TEST36\SmartBehaviour
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 1000000
    time_horizon: 10
    summary_freq: 5000
    threaded: true
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  run_id: TEST36infer
  initialize_from: TEST36
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: true
  results_dir: results
torch_settings:
  device: null
debug: false
